# Generated by Django 2.0.5 on 2018-06-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0005_auto_20180614_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=5, verbose_name='dia(s)')),
                ('title', models.CharField(max_length=50, verbose_name='titulo')),
                ('description_es', models.TextField(verbose_name='descripcion en español')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='descripcion en ingles')),
                ('description_pt', models.TextField(blank=True, null=True, verbose_name='descripcion en español')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tour')),
            ],
            options={
                'verbose_name': 'Itinerary',
            },
        ),
    ]
