# Generated by Django 2.0.5 on 2018-06-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerario', '0002_auto_20180614_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['-created'], 'verbose_name': 'Itinerario'},
        ),
    ]
