# Generated by Django 2.0.5 on 2018-06-12 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miscelanea', '0003_auto_20180612_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('place', models.CharField(max_length=50, verbose_name='lugar')),
                ('duration', models.CharField(max_length=10, verbose_name='duracion')),
                ('corver', models.ImageField(upload_to='portada', verbose_name='portada')),
                ('video', models.CharField(max_length=250, verbose_name='video')),
                ('description_es', models.TextField(verbose_name='descripcion en español')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='descripcion en ingles')),
                ('description_pt', models.TextField(blank=True, null=True, verbose_name='descripcion en portugues')),
                ('price_sol', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio en soles')),
                ('price_des_sol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='precio en soles')),
                ('price_dolar', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio en dolares')),
                ('price_des_dolar', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio en dolares')),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscelanea.Category', verbose_name='categoria')),
                ('include', models.ManyToManyField(to='miscelanea.Include', verbose_name='Que incluye')),
                ('no_include', models.ManyToManyField(to='miscelanea.NoInclude', verbose_name='que no incluye')),
            ],
            options={
                'verbose_name': 'Tour',
                'ordering': ['-created'],
            },
        ),
    ]
