# Generated by Django 2.0.5 on 2018-06-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20180612_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price_des_dolar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='precio con descuento en dolares'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_des_sol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='precio en con descuento soles'),
        ),
    ]
