# Generated by Django 2.0.5 on 2018-06-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20180612_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='corver',
            new_name='cover',
        ),
    ]
