# Generated by Django 2.0.5 on 2018-06-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20180612_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price_des_dolar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='precio con descuento en dolares'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_des_sol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='precio en con descuento soles'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_dolar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='precio en dolares'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_sol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='precio en soles'),
        ),
    ]
