# Generated by Django 2.0.5 on 2018-06-08 15:46

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Incluye',
                'ordering': ['-created'],
                'verbose_name_plural': 'Incluye',
            },
        ),
        migrations.CreateModel(
            name='NoInclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'No Incluye',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_modified',
        ),
    ]
